# frozen_string_literal: true

name 'algosec'
maintainer 'AlgoSec Systems'
maintainer_email 'support@algosec.com'
license 'MIT'
description 'Leverage AlgoSec\'s business-driven security policy management solution.'
long_description 'Leverage AlgoSec\'s business-driven security policy management solution.'
version '1.2.0'

chef_version '>= 12'

issues_url 'https://github.com/algosec/algosec-chef/issues'
source_url 'https://github.com/algosec/algosec-chef'

supports 'windows'
supports 'mac_os_x'
supports 'debian'
supports 'ubuntu'
supports 'centos'
supports 'redhat'
supports 'fedora'
supports 'freebsd'
supports 'amazon'
supports 'scientific'
supports 'arch'
supports 'suse'
supports 'xenserver'
supports 'smartos'
supports 'oracle'
